

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./store/storeProvider";
import { Navbar } from "@/components/Navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider"
import SessionWrapper from "@/components/sessionWrpper/sessionWrpper";
import { Footer } from "./footer/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
       

         
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
               <SessionWrapper>
      <Navbar/>
        {children} 
        <Footer/>
        </SessionWrapper>
          </ThemeProvider>
      
      </body>
    </html>
        </StoreProvider>
  );
}
